api:
  type: config_object
  label: 'OCHA local groups API settings'
  mapping:
    endpoint:
      type: string
      label: 'API endpoint'
field.formatter.settings.ocha_local_groups_default:
  type: mapping
  label: 'Default formatter settings'
  mapping:
    output:
      type: string
      label: 'Output'
    output_global_cluster:
      type: string
      label: 'Global cluster'
    output_lead_agencies:
      type: string
      label: 'Lead agencies'
    output_partners:
      type: string
      label: 'Partners'
    output_activation_document:
      type: string
      label: 'Activation document'
    output_operations:
      type: string
      label: 'Operations'
