_core:
  default_config_hash: yOPH6uEZYRHbg2OFP-bze0jGr06fI-Gr_66W-vA8Faw
report-only:
  enable: true
  directives:
    connect-src:
      base: self
      sources:
        - kmp.hpc.tools
        - gov-bam.nr-data.net
        - www.google-analytics.com
        - '*.analytics.google.com'
    font-src:
      base: self
      sources:
        - 'data:'
        - fonts.gstatic.com
    frame-src:
      base: ''
      sources:
        - data.humdata.org
    img-src:
      base: self
      sources:
        - 'data:'
        - '*.tile.openstreetmap.org'
        - www.google-analytics.com
        - www.googletagmanager.com
        - www.gstatic.com
        - translate.google.com
    object-src:
      base: none
    script-src:
      base: self
      flags:
        - unsafe-inline
      sources:
        - fonts.googleapis.com
        - www.gstatic.com
        - www.google.com
        - www.googletagmanager.com
        - www.youtube.com
        - cdn.jsdelivr.net
        - js-agent.newrelic.com
        - gov-bam.nr-data.net
        - '*.google-analytics.com'
    script-src-attr:
      base: self
    script-src-elem:
      base: self
      flags:
        - unsafe-inline
      sources:
        - fonts.googleapis.com
        - www.gstatic.com
        - www.google.com
        - www.googletagmanager.com
        - www.youtube.com
        - cdn.jsdelivr.net
        - js-agent.newrelic.com
        - gov-bam.nr-data.net
        - '*.google-analytics.com'
    style-src:
      base: self
      flags:
        - unsafe-inline
    style-src-attr:
      base: self
      flags:
        - unsafe-inline
    style-src-elem:
      base: self
      flags:
        - unsafe-inline
    frame-ancestors:
      base: self
  reporting:
    plugin: sitelog
enforce:
  enable: true
  directives:
    object-src:
      base: none
    frame-ancestors:
      base: self
  reporting:
    plugin: sitelog
