<?php

/**
 * @file
 * OCHA Document store connector.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Alter base url of the endpoints.
 */
function ocha_docstore_files_get_endpoint_base($endpoint) {
  $base_url = \Drupal::config('ocha_docstore_files.settings')->get('endpoint_url');

  if (empty($base_url)) {
    return $endpoint;
  }

  $path = parse_url($endpoint, PHP_URL_PATH);
  return rtrim($base_url, '/') . $path;
}

/**
 * Alter api-key of the endpoints.
 */
function ocha_docstore_files_get_endpoint_apikey($apikey) {
  $endpoint_apikey = \Drupal::config('ocha_docstore_files.settings')->get('endpoint_apikey');

  if (empty($endpoint_apikey)) {
    return $apikey;
  }

  return $endpoint_apikey;
}

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 *
 * Ensure external entities created via an inline entity form are saved.
 */
function ocha_docstore_files_inline_entity_form_entity_form_alter(array &$entity_form, FormStateInterface &$form_state) {
  if (isset($entity_form['#entity']) && is_a($entity_form['#entity'], '\Drupal\external_entities\Entity\ExternalEntity')) {
    $entity_form['#save_entity'] = TRUE;
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function ocha_docstore_files_entity_type_alter(array &$entity_types) {
  if (!empty($entity_types['external_entity_type'])) {
    $external_entity_type_config = $entity_types['external_entity_type'];

    // Get the existing external entity type configurations.
    /* @var \Drupal\external_entities\ExternalEntityTypeInterface[] $external_entity_types */
    $external_entity_types = \Drupal::entityTypeManager()->createHandlerInstance(
      $external_entity_type_config->getHandlerClass('storage'),
      $external_entity_type_config
    )->loadMultiple();

    foreach ($external_entity_types as $external_entity_type) {
      $entity_types[$external_entity_type->id()]->setHandlerClass('access', 'Drupal\ocha_docstore_files\OchaExternalEntityAccessControlHandler');
    }
  }
}
